Custom converters (#4088): A bit better conversion errors.
Don't include 'ValueError' prefix in errors reported to user
unnecessarily. In practice change the final error from

    ValueError: Argument 'x' got value 'inv' that cannot be converted to X: ValueError: reported errror

to

    ValueError: Argument 'x' got value 'inv' that cannot be converted to X: reported errror

Documentation will also recommend using ValueErrors for reporting
errors.